/**
 * A deliberately small, deterministic JSONPath subset — enough to address every
 * region a compressor omits, and small enough to audit.
 *
 * Supported: `$`, `.key`, `["key"]`, `[n]`, `[*]`, `[start:end]`.
 * Not supported (and rejected, never silently ignored): recursive descent `..`,
 * filters, expressions. Compressor locators are generated by `formatJsonPath`, so
 * the writable surface and the readable surface are the same grammar by construction.
 */

import { ContextStoreError } from "./types.js";

export type JsonPathSegment =
  | { kind: "key"; key: string }
  | { kind: "index"; index: number }
  | { kind: "wildcard" }
  | { kind: "slice"; start: number; end: number };

export function parseJsonPath(path: string): JsonPathSegment[] {
  if (path !== "$" && !path.startsWith("$.") && !path.startsWith("$[")) {
    throw new ContextStoreError("invalid-path", "JSONPath must start at the document root `$`");
  }
  const segments: JsonPathSegment[] = [];
  let i = 1;
  while (i < path.length) {
    const ch = path[i];
    if (ch === ".") {
      if (path[i + 1] === ".") {
        throw new ContextStoreError("invalid-path", "Recursive descent `..` is not supported");
      }
      let j = i + 1;
      while (j < path.length && /[A-Za-z0-9_$-]/.test(path[j] ?? "")) j++;
      if (j === i + 1) throw new ContextStoreError("invalid-path", "Empty key after `.`");
      segments.push({ kind: "key", key: path.slice(i + 1, j) });
      i = j;
      continue;
    }
    if (ch === "[") {
      const close = path.indexOf("]", i);
      if (close < 0) throw new ContextStoreError("invalid-path", "Unclosed `[` in JSONPath");
      const inner = path.slice(i + 1, close);
      segments.push(parseBracket(inner));
      i = close + 1;
      continue;
    }
    throw new ContextStoreError("invalid-path", "Unexpected character in JSONPath");
  }
  return segments;
}

function parseBracket(inner: string): JsonPathSegment {
  if (inner === "*") return { kind: "wildcard" };
  const quoted = /^"([^"]*)"$/.exec(inner) ?? /^'([^']*)'$/.exec(inner);
  if (quoted) return { kind: "key", key: quoted[1] ?? "" };
  const slice = /^(\d+):(\d+)$/.exec(inner);
  if (slice) {
    const start = Number(slice[1]);
    const end = Number(slice[2]);
    if (end < start) throw new ContextStoreError("invalid-path", "Slice end precedes start");
    return { kind: "slice", start, end };
  }
  if (/^\d+$/.test(inner)) return { kind: "index", index: Number(inner) };
  throw new ContextStoreError("invalid-path", "Unsupported bracket selector");
}

/** Canonical rendering. `parseJsonPath(formatJsonPath(s))` round-trips. */
export function formatJsonPath(segments: readonly JsonPathSegment[]): string {
  let out = "$";
  for (const s of segments) {
    if (s.kind === "key") out += /^[A-Za-z_$][A-Za-z0-9_$-]*$/.test(s.key) ? `.${s.key}` : `[${JSON.stringify(s.key)}]`;
    else if (s.kind === "index") out += `[${s.index}]`;
    else if (s.kind === "wildcard") out += "[*]";
    else out += `[${s.start}:${s.end}]`;
  }
  return out;
}

/**
 * Resolve a path against a parsed document. A missing key/index resolves to
 * `undefined` rather than throwing: "not present" is a legitimate retrieval answer.
 */
export function applyJsonPath(root: unknown, segments: readonly JsonPathSegment[]): unknown {
  let current: unknown = root;
  for (const seg of segments) {
    if (current === null || current === undefined) return undefined;
    if (seg.kind === "key") {
      if (typeof current !== "object" || Array.isArray(current)) return undefined;
      current = (current as Record<string, unknown>)[seg.key];
    } else if (seg.kind === "index") {
      if (!Array.isArray(current)) return undefined;
      current = current[seg.index];
    } else if (seg.kind === "wildcard") {
      if (Array.isArray(current)) current = [...current];
      else if (typeof current === "object") current = Object.values(current as Record<string, unknown>);
      else return undefined;
    } else {
      if (!Array.isArray(current)) return undefined;
      current = current.slice(seg.start, seg.end);
    }
  }
  return current;
}
