/**
 * v0.3.3 Repository Structure Compression — deterministic, NO LLM.
 *
 * Goal: reduce the tokens an AI coding agent reads while preserving the repository's
 * structure and PUBLIC INTERFACE. A compressed source file keeps imports/exports,
 * declarations, and signatures (with doc comments), and omits implementation bodies.
 * Everything here is derived from the syntax tree only — never inferred or summarized.
 *
 * Responsibilities are split so the core never grows a per-language switch:
 *   SourceCompressor   — one per language (registered in the CompressorRegistry)
 *   CompressorRegistry — routes a file to the right compressor; falls back to FULL
 *
 * Failure is always safe: if a file cannot be parsed/compressed, it is kept FULL with
 * a recorded warning — never emptied, never partially compressed, never excluded.
 */

/** How a file is represented in the Prepared Repository. */
export type ContextRepresentation = "full" | "compressed" | "excluded";

/** A structural symbol extracted from the syntax tree (fact, not inference). */
export interface ExtractedSymbol {
  kind:
    | "import"
    | "export"
    | "namespace"
    | "module"
    | "class"
    | "interface"
    | "type"
    | "enum"
    | "function"
    | "method"
    | "constructor"
    | "field"
    | "constant"
    | "decorator";
  name: string;
  /** The rendered signature line (no body), when applicable. */
  signature?: string;
  /** True when the symbol is exported / public. */
  exported?: boolean;
  /** 1-based line where the symbol starts (best-effort, deterministic). */
  line?: number;
  /** Nested symbols (e.g. class members). */
  children?: ExtractedSymbol[];
}

export interface CompressionWarning {
  /**
   * `parse-failed` = the parser loaded but the source has syntax errors.
   * `compressor-unavailable` = the language compressor (e.g. the TypeScript parser)
   * could not be loaded at all — a DIFFERENT cause with a different remedy.
   */
  code:
    | "parse-failed"
    | "compressor-unavailable"
    | "unsupported-language"
    | "empty-output"
    | "partial"
    | "too-small";
  message: string;
}

export interface CompressionInput {
  /** Repo-relative POSIX path (never absolute). */
  relpath: string;
  content: string;
  /** Optional explicit language id; otherwise inferred from the path/content. */
  languageId?: string;
}

export interface CompressionResult {
  representation: "full" | "compressed";
  originalTokens: number;
  compressedTokens: number;
  /** The delivered content — compressed structure, or the original when kept full. */
  content: string;
  symbols: ExtractedSymbol[];
  warnings: CompressionWarning[];
}

/**
 * A per-language compressor. `supports` is a cheap check (extension + optional content
 * sniff); `compress` produces a syntactically-recognizable, body-omitted representation.
 * A compressor MUST NOT throw for malformed input — it returns a FULL result with a
 * `parse-failed` warning so the registry can keep the original.
 */
export interface SourceCompressor {
  readonly languageId: string;
  supports(path: string, content: string): boolean;
  compress(input: CompressionInput): Promise<CompressionResult>;
}

/** The header note prepended to every compressed file. Never includes an absolute path. */
export function compressionHeader(relpath: string): string {
  return (
    "// Generated by Yuhi structure compression.\n" +
    "// Implementation bodies were omitted.\n" +
    `// Original source: ${relpath}\n`
  );
}
